include_defs('//bucklets/maven_jar.bucklet')

maven_jar(
  name = 'log4j',
  id = 'log4j:log4j:1.2.17',
  sha1 = '5af35056b4d257e4b64b9e8069c0746e8b08629f',
  license = 'Apache2.0',
  exclude = ['META-INF/LICENSE', 'META-INF/NOTICE'],
)
