include_defs('//bucklets/maven_jar.bucklet')

maven_jar(
  name = 'jcl-over-slf4j',
  id = 'org.slf4j:jcl-over-slf4j:1.7.7',
  sha1 = '56003dcd0a31deea6391b9e2ef2f2dc90b205a92',
  license = 'slf4j',
)

maven_jar(
  name = 'log4j',
  id = 'log4j:log4j:1.2.17',
  sha1 = '5af35056b4d257e4b64b9e8069c0746e8b08629f',
  license = 'Apache2.0',
  exclude = ['META-INF/LICENSE', 'META-INF/NOTICE'],
)
